# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01af19727a9f6eae6175f9ef1b1903038606bfe0e9c1e859234debed0920435035a5d7206a8a5386303e68d5ea5f4fab75f59bf17f691c7ec1da190562d84985

test:
  secret_key_base: e13071d741b110e73a59bf3fe381f61de5e5b2ce7fd890bbd6937b1d8cc516a641b03495754a253c8870eb5878bfd5d81621139ba5ea03087bb1517ac6d902a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
